version: '3'

services:
  fiegnclient:
    container_name: feignclient
    hostname: feignclient
    image: feignclient:latest
    ports:
      - "8080:8080"
    environment:
      - TRACING_ENDPOINT=http://jaegertracing:4317/v1/traces
    networks:
      - feignclient
    depends_on:
      - jaeger
      - prometheus

  jaeger:
    container_name: jaegertracing
    hostname: jaegertracing
    image: jaegertracing/all-in-one
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - feignclient

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - feignclient

networks:
  feignclient:
    driver: bridge
